# Usa la imagen base de Node.js, ya que Uptime Kuma está basado en Node.js
FROM node:16

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios para la aplicación
COPY . .

# Instala las dependencias
RUN npm install

# Expone el puerto 3001
EXPOSE 3001

# Comando para iniciar la aplicación
CMD ["npm", "start"]